# Generated by Django 5.2.2 on 2025-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='surname',
        ),
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
