# Generated by Django 5.2.2 on 2025-06-06 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_submission_surname_submission_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_submissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('не рассмотрено', 'Не рассмотрено'), ('рассматривается', 'Рассматривается'), ('рассмотрено', 'Рассмотрено')], default='не рассмотрено', max_length=20),
        ),
    ]
