# Generated by Django 5.2.2 on 2025-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_submission_user_alter_submission_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('Development', 'Стратегическое планирование и развитие бизнеса'), ('Organization', 'Организационная структура и управление персоналом'), ('Finances', 'Финансовое планирование и бюджетирование'), ('Marketing', 'Маркетинг и продвижение'), ('Automatization', 'Автоматизация бизнес-процессов'), ('Bureaucracy', 'Юридическое сопровождение и лицензирование'), ('Investments', 'Инвестиции и поиск партнёров')], max_length=100),
        ),
    ]
