# Generated by Django 5.2.2 on 2025-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_feedback_assigned_to_delete_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
